---
apiVersion: v1
kind: Secret
metadata:
  name: "test054-credentials"
  namespace: "jenkins"
  labels:
    provider: agilestacks.com
    project: jenkins
    qualifier: credentials
data:
  password: ""
---
apiVersion: "jenkins.agilestacks.com/v1"
kind: Credentials
metadata:
  name: "test054-credentials"
spec:
  domain: "global"
  description: "Docker registry authorization for test054"
  usernamePassword:
    username: ""
    password:
      secretKeyRef:
        name: "test054-credentials"
        key: password
